# test
name: Deploy to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - name: Build, tag, and push image to Amazon ECR
        env:
          TABLE_CHECK_WEB_BOOKING_URL: ${{secrets.TABLE_CHECK_WEB_BOOKING_URL}}
        run: |
          export TABLE_CHECK_WEB_BOOKING_URL="${TABLE_CHECK_WEB_BOOKING_URL}"
          /bin/bash deploy/deploy.sh --noprompt --staging
